# secrets.yaml


apiVersion: v1
kind: Secret
metadata:
  name: CONFIG_APP_NAME-secrets
  namespace: CONFIG_NAMESPACE
type: Opaque
stringData:
  rootpassword: rootUsersPassword123
  database: example-db
  username: example-user
  password: exampleUsersPassword123